sonar.issue.ignore.multicriteria=r1,r2,r3

sonar.issue.ignore.multicriteria.r1.ruleKey=Web:S6819
sonar.issue.ignore.multicriteria.r1.resourceKey=**/*.html

sonar.issue.ignore.multicriteria.r2.ruleKey=typescript:S7649
sonar.issue.ignore.multicriteria.r2.resourceKey=**/*.ts

sonar.issue.ignore.multicriteria.r3.ruleKey=typescript:S7653
sonar.issue.ignore.multicriteria.r3.resourceKey=**/*.ts
