import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  menus = [
    { label: 'Portinari HTML Framework', link: '/', subItems: [
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
      { label: 'Nivel 2', link: '/' },
    ] },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
    { label: 'Portinari HTML Framework', link: '/' },
  ];
}
