export const poRichTextLiteralsDefault = {
  en: {
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    left: 'Left',
    center: 'Center',
    right: 'Right',
    justify: 'Justify',
    textColor: 'Text color',
    unorderedList: 'Bulleted list',
    insertLink: 'Insert link',
    linkTextLabel: 'Text with link',
    linkUrlTextHelper: 'Paste in the text box below the copied browser link',
    linkUrlTextPlaceholder: 'Enter the link address that will be attached to the text.',
    cancel: 'Cancel',
    editLink: 'Edit link',
    insert: 'Insert',
    insertImage: 'Insert image',
    urlImage: 'URL image'
  },
  es: {
    bold: 'Negrita',
    italic: 'Cursiva',
    underline: 'Subrayado',
    left: 'Izquierda',
    center: 'Centro',
    right: 'Derecha',
    justify: 'Justificado',
    textColor: 'Color del texto',
    unorderedList: 'Lista con viñetas',
    insertLink: 'Insertar el link',
    linkTextLabel: 'Texto con enlace',
    linkUrlTextHelper: 'Pegue en el cuadro de texto debajo del enlace del navegador copiado',
    linkUrlTextPlaceholder: 'Ingrese la dirección del enlace que se adjuntará al texto.',
    cancel: 'Cancelar',
    editLink: 'Editar enlace',
    insert: 'Insertar',
    insertImage: 'Insertar imagen',
    urlImage: 'Imagen URL'
  },
  pt: {
    bold: 'Negrito',
    italic: 'Itálico',
    underline: 'Sublinhado',
    left: 'Esquerda',
    center: 'Centro',
    right: 'Direita',
    justify: 'Justificado',
    textColor: 'Cor do texto',
    unorderedList: 'Lista com marcadores',
    insertLink: 'Inserir link',
    linkTextLabel: 'Texto com link',
    linkUrlTextHelper: 'Cole na caixa de texto abaixo o link copiado do navegador',
    linkUrlTextPlaceholder: 'Insira o endereço do link que será anexado ao texto',
    cancel: 'Cancelar',
    editLink: 'Editar link',
    insert: 'Inserir',
    insertImage: 'Inserir imagem',
    urlImage: 'Imagem em URL'
  },
  ru: {
    bold: 'Жирный',
    italic: 'Италик',
    underline: 'Подчеркивание',
    left: 'Влево',
    center: 'Центр',
    right: 'Вправо',
    justify: 'Растянуть',
    textColor: 'Цвет текста',
    unorderedList: 'Список',
    insertLink: 'Вставьте ссылку',
    linkTextLabel: 'Текст со ссылкой',
    linkUrlTextHelper: 'Вставьте в текстовое поле ниже скопированную ссылку',
    linkUrlTextPlaceholder: 'Вставьте ссылку для привязки к тексту',
    cancel: 'Отмена',
    editLink: 'Редактировать ссылку',
    insert: 'Вставить',
    insertImage: 'Вставить изображение',
    urlImage: 'Ссылка на изображение'
  }
};
